In [7]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [8]:
load_dotenv()

True

In [9]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [10]:
df_funcionario = pd.read_sql(
    "SELECT * FROM raw.funcionario",
    engine
)

In [11]:
pd.read_sql("""
SELECT DISTINCT nome
FROM raw.funcionario;
""", engine)

                nome
0       Larissa Melo
1      Roberto Alves
2     Thiago Barbosa
3       Diego Castro
4     Amanda Ribeiro
5        João Pedro
6       Jessica Lima
7      Bruno Martins
8      Vanessa Lopes
9       CARLOS SOUZA
10      Camila Rocha
11    Maria Oliveira
12    Ricardo Mendes
13       Aline Souza
14    Patricia Gomes
15      Juliana Lima
16    Pedro Henrique
17       Ana Beatriz
18  Bianca Fernandes
19      Felipe Nunes
20    Gabriel Araújo
21    Lucas Ferreira
22       Carla Dias
23        Joao Silva
24   Eduardo Santos
25      Marcos Paulo
26       Paulo César
27      Renata Moura
28   Cláudio Pereira
29    Fernanda Costa

In [12]:
pd.read_sql("""
SELECT DISTINCT telefone
FROM raw.funcionario;
""", engine)

          telefone
0      85955554444
1   (85)96655-7777
2      85944445555
3   (85)91111-0000
4   (85)98877-3333
5      85988881111
6   (85)93333-5555
7   (85)97766-5555
8   (85)95544-9999
9      85966663333
10     85922221111
11  (85)92222-8888
12   85 99999-3333
13     85933334444
14     85988885555
15     85911110000
16     85944443333
17     85977776666
18  (85)98888-4444
19     85999992222
20  (85)94444-3333
21  (85)96666-9999
22     85933332222
23     85977772222
24  (85)99999-1111
25  (85)97777-7777
26     85900009999
27  (85)95555-1111
28     85966665555

In [13]:
pd.read_sql("""
SELECT DISTINCT email
FROM raw.funcionario;
""", engine)

                  email
0      CARLOS@EMAIL.COM
1     vanessa@email.com
2      camila@email.com
3      maria@email.com
4        joao@email.com
5    fernanda@email.com
6       carla@email.com
7         ana@email.com
8    JESSICA@EMAIL.COM
9      RENATA@EMAIL.COM
10   eduardo@email.com
11     thiago@email.com
12   PATRICIA@EMAIL.COM
13    ricardo@email.com
14      diego@email.com
15    claudio@email.com
16    ROBERTO@EMAIL.COM
17    gabriel@email.com
18     felipe@email.com
19     amanda@gmail.com
20      pedro@gmail.com
21          paulo@email
22      ALINE@EMAIL.COM
23      bruno@email.com
24          lucas@email
25    LARISSA@EMAIL.COM
26       JOAO@EMAIL.COM
27    JULIANA@EMAIL.COM
28     marcos@email.com
29     BIANCA@EMAIL.COM

In [14]:
pd.read_sql("""
SELECT DISTINCT status
FROM raw.funcionario;
""", engine)

    status
0    ativo
1    Ativo
2  Inativo
3    ATIVO