In [46]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [47]:
load_dotenv()

True

In [48]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [49]:
df_loja = pd.read_sql("SELECT * FROM raw.loja", engine)

In [50]:
df_loja.head()

,loja_id,endereco_id,nome,telefone,email,status
0,1,1,Concessionária Fortaleza Centro,(85)4000-1001,centro@concessionaria.com,Ativa
1,2,2,concessionária fortaleza centro,8540001001,CENTRO@CONCESSIONARIA.COM,ativa
2,3,3,Concessionária Aldeota,(85)4000-1002,aldeota@concessionaria.com,ATIVA
3,4,4,CONCESSIONÁRIA ALDEOTA,85 4000-1002,ALDEOTA@CONCESSIONARIA.COM,ativa
4,5,5,Concessionária Meireles,(85)4000-1003,meireles@concessionaria.com,Ativa

In [51]:
pd.read_sql("SELECT DISTINCT nome FROM raw.loja", engine)

                                 nome
0                            Loja Sul
1             Concessionária Meireles
2              Concessionária Aldeota
3     Concessionária Fortaleza Centro
4             Concessionaria Meireles
5              CONCESSIONÁRIA ALDEOTA
6                          LOJA NORTE
7                          Loja Norte
8                       Loja Oeste
9              Concessionária Benfica
10   concessionária fortaleza centro
11           Concessionária Maracanaú
12             Concessionária Caucaia
13              Concessionária Papicu
14                         Loja Leste

In [52]:
pd.read_sql("SELECT DISTINCT telefone FROM raw.loja", engine)

         telefone
0   (85)4000-1003
1   (85)4000-1009
2      8540001008
3   (85)4000-1004
4   (85)4000-1008
5    85 4000-1002
6   (85)4000-1002
7   (85)4000-1001
8   (85)4000-1006
9   (85)4000-1010
10     8540001003
11  (85)4000-1007
12   85 4000-1005
13     8540001001
14   85 4000-1011

In [53]:
pd.read_sql("SELECT email FROM raw.loja", engine)

                             email
0        centro@concessionaria.com
1        CENTRO@CONCESSIONARIA.COM
2       aldeota@concessionaria.com
3      ALDEOTA@CONCESSIONARIA.COM
4      meireles@concessionaria.com
5      MEIRELES@CONCESSIONARIA.COM
6                     papicu@email
7       BENFICA@CONCESSIONARIA.COM
8       caucaia@concessionaria.com
9    maracanau@concessionaria.com
10        norte@concessionaria.com
11        NORTE@CONCESSIONARIA.COM
12          sul@concessionaria.com
13        LESTE@CONCESSIONARIA.COM
14       oeste@concessionaria.com

In [54]:
pd.read_sql("SELECT status FROM raw.loja", engine)

     status
0     Ativa
1     ativa
2     ATIVA
3     ativa
4     Ativa
5     ATIVA
6     Ativa
7     ativa
8     ATIVA
9     Ativa
10    ativa
11    ATIVA
12  Inativa
13    ATIVA
14    ativa

In [55]:
df_loja.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   loja_id      15 non-null     int64
 1   endereco_id  15 non-null     int64
 2   nome         15 non-null     str
 3   telefone     15 non-null     str
 4   email        15 non-null     str
 5   status       15 non-null     str
dtypes: int64(2), str(4)
memory usage: 852.0 bytes