In [12]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [13]:
load_dotenv()

True

In [14]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [ ]:
df_fornecedor = pd.read_sql("SELECT * FROM raw.fornecedor", engine)

In [16]:
df_fornecedor.head()

,fornecedor_id,endereco_id,nome,cnpj,telefone,email,status
0,1,1,Auto Motors LTDA,12.345.678/0001-01,(11)4000-1001,contato@automotors.com.br,Ativo
1,2,2,auto motors ltda,12345678000102,1140001002,CONTATO@AUTOMOTORS.COM.BR,ativo
2,3,3,Premium Veículos,23.456.789/0001-03,(21)4000-1003,vendas@premium.com.br,ATIVO
3,4,4,PREMIUM VEICULOS,23456789000104,2140001004,VENDAS@PREMIUM.COM.BR,ativa
4,5,5,Brasil Car,34.567.890/0001-05,(31)4000-1005,contato@brasilcar.com.br,Ativo

In [17]:
pd.read_sql("""
SELECT DISTINCT nome
FROM raw.fornecedor;
""", engine)

                  nome
0       Prime Veículos
1           Top Motors
2       Luxury Imports
3        Fast Motors
4        Global Motors
5     Auto Motors LTDA
6           Speed Cars
7     Premium Veículos
8           Brasil Car
9     PREMIUM VEICULOS
10   auto motors ltda
11         brasil car
12         Auto Center
13      Nacional Autos
14            Mega Car

In [18]:
pd.read_sql("""
SELECT DISTINCT cnpj
FROM raw.fornecedor;
""", engine)

                  cnpj
0   12.345.678/0001-01
1   90.123.456/0001-12
2   22.334.455/0001-15
3   67.890.123/0001-09
4       12345678000102
5   34.567.890/0001-05
6   11.223.344/0001-14
7   45.678.901/0001-07
8   56.789.012/0001-08
9       34567890000106
10  23.456.789/0001-03
11  89.012.345/0001-11
12  01.234.567/0001-13
13      23456789000104
14  78.901.234/0001-10

In [19]:
pd.read_sql("""
SELECT DISTINCT telefone 
FROM raw.fornecedor 
""", engine)

         telefone
0   (21)4000-1003
1   (41)4000-1007
2   (31)4000-1005
3   (81)4000-1013
4      6140001011
5      2140001004
6   (85)4000-1015
7   (11)4000-1001
8      3140001006
9   (61)4000-1010
10     1140001002
11  (71)4000-1012
12  (51)4000-1009
13     8140001014
14     4140001008

In [20]:
pd.read_sql("""
SELECT DISTINCT email
FROM raw.fornecedor
""", engine)

                        email
0      prime@veiculos.com.br
1    CONTATO@BRASILCAR.COM.BR
2       nacional@autos.com.br
3             MEGA@CAR.COM.BR
4       vendas@premium.com.br
5         fast@motors.com.br
6   contato@automotors.com.br
7      VENDAS@PREMIUM.COM.BR
8           speed@cars.com.br
9   CONTATO@AUTOMOTORS.COM.BR
10       autocenter@email.com
11      LUXURY@IMPORTS.COM.BR
12          TOP@MOTORS.COM.BR
13               global@email
14   contato@brasilcar.com.br

In [21]:
pd.read_sql("""
SELECT DISTINCT email 
FROM raw.fornecedor
""", engine)

                        email
0      prime@veiculos.com.br
1    CONTATO@BRASILCAR.COM.BR
2       nacional@autos.com.br
3             MEGA@CAR.COM.BR
4       vendas@premium.com.br
5         fast@motors.com.br
6   contato@automotors.com.br
7      VENDAS@PREMIUM.COM.BR
8           speed@cars.com.br
9   CONTATO@AUTOMOTORS.COM.BR
10       autocenter@email.com
11      LUXURY@IMPORTS.COM.BR
12          TOP@MOTORS.COM.BR
13               global@email
14   contato@brasilcar.com.br

In [22]:
pd.read_sql("""
SELECT DISTINCT status 
FROM raw.fornecedor
""", engine)

    status
0    ativo
1    Ativo
2  Inativo
3    ativa
4    ATIVA
5    ATIVO

In [25]:
pd.read_sql("""
SELECT *
FROM raw.fornecedor
WHERE nullif(
    regexp_replace(telefone, '[^0-9]', '', 'g'),
    ''
) IS NULL;
""", engine)

Empty DataFrame
Columns: [fornecedor_id, endereco_id, nome, cnpj, telefone, email, status]
Index: []

In [27]:
pd.read_sql("""
SELECT
    regexp_replace(telefone, '[^0-9]', '', 'g') AS telefone,
    COUNT(*) AS quantidade
FROM raw.fornecedor
GROUP BY regexp_replace(telefone, '[^0-9]', '', 'g')
HAVING COUNT(*) > 1;
""", engine)

Empty DataFrame
Columns: [telefone, quantidade]
Index: []

In [ ]:
pd.read_sql("""
SELECT
    lower(trim(email)) AS email,
    COUNT(*) AS quantidade
FROM raw.fornecedor
GROUP BY lower(trim(email))
HAVING COUNT(*) > 1;
""", engine)

In [ ]:
pd.read_sql("""
SELECT
    regexp_replace(cnpj, '[^0-9]', '', 'g') AS cnpj,
    COUNT(*) AS quantidade
FROM raw.fornecedor
GROUP BY regexp_replace(cnpj, '[^0-9]', '', 'g')
HAVING COUNT(*) > 1;
""", engine)

In [28]:
df_fornecedor.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fornecedor_id  15 non-null     int64
 1   endereco_id    15 non-null     int64
 2   nome           15 non-null     str
 3   cnpj           15 non-null     str
 4   telefone       15 non-null     str
 5   email          15 non-null     str
 6   status         15 non-null     str
dtypes: int64(2), str(5)
memory usage: 972.0 bytes