In [70]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [71]:
load_dotenv()

True

In [72]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [73]:
df_marca = pd.read_sql("SELECT * FROM raw.marca", engine)

In [74]:
df_marca.head()

   marca_id      nome pais_origem status
0         1    Toyota       Japão  Ativa
1         2   toyota        japao  ativa
2         3    TOYOTA          JP  ATIVA
3         4     Honda       Japão  Ativa
4         5     HONDA      JAPAO   ativa

In [75]:
pd.read_sql("""
SELECT DISTINCT nome
FROM raw.marca;
""", engine)

               nome
0             JEEP
1        VOLKSWAGEN
2              byd
3             FORD
4             Honda
5              Ford
6            Hondaa
7    Mercedes Benz
8         Chevrolet
9            NISSAN
10              bmw
11
12          Peugeot
13              GWM
14          Porsche
15          hyundai
16            Toyta
17           TOYOTA
18           Mazdaa
19             Audi
20            HONDA
21            Tesla
22          Renault
23              Kia
24          Bugatti
25            CHERY
26            Chery
27      Lamborghini
28    Mercedes-Benz
29             AUDI
30             Fiat
31       Land Rover
32             Jeep
33            Volvo
34            FIAT
35          PORSCHE
36       MITSUBISHI
37           Nissan
38          toyota
39              KIA
40          Citroën
41          Hyundai
42          Citroen
43          PEUGEOT
44          RENAULT
45            TESLA
46       Mitsubishi
47              BYD
48       CHEVROLET
49       LAND ROVER
50              BMW
51            VOLVO
52       Volkswagen
53          Ferrari
54           Toyota

In [76]:
pd.read_sql("""
SELECT DISTINCT pais_origem
FROM raw.marca;
""", engine)

       pais_origem
0           França
1         Alemanha
2           franca
3           Suécia
4           Suecia
5    Coreia do Sul
6         alemanha
7   Estados Unidos
8      Reino Unido
9            China
10           japao
11        ALEMANHA
12              JP
13          Italia
14          Franca
15          Coreia
16           china
17           Japão
18           CHINA
19         França
20              UK
21           Japao
22          Brasil
23          JAPAO
24             EUA
25          Itália
26   Coréia do Sul

In [77]:
pd.read_sql("""
SELECT DISTINCT status
FROM raw.marca;
""", engine)

    status
0  inativa
1      NaN
2    Ativa
3    ATIVA
4  Inativa
5    ativa

In [78]:
df_marca.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   marca_id     56 non-null     int64
 1   nome         56 non-null     str
 2   pais_origem  56 non-null     str
 3   status       55 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.9 KB

In [79]:
df_marca.describe(include="all")

         marca_id    nome pais_origem status
count   56.000000      56          56     55
unique        NaN      55          27      5
top           NaN  Mazdaa       Japão  Ativa
freq          NaN       2           8     30
mean    28.500000     NaN         NaN    NaN
std     16.309506     NaN         NaN    NaN
min      1.000000     NaN         NaN    NaN
25%     14.750000     NaN         NaN    NaN
50%     28.500000     NaN         NaN    NaN
75%     42.250000     NaN         NaN    NaN
max     56.000000     NaN         NaN    NaN

In [80]:
df_marca.isnull().sum()

marca_id       0
nome           0
pais_origem    0
status         1
dtype: int64

In [81]:
df_marca.duplicated().sum()

np.int64(0)